image: node

stages:
  - test
  - deploy

before_script:
  - npm config set prefix /usr/local
  - npm install -g serverless
  - npm install

test:
  stage: test
  script:
    - npm run test
  only:
    - master
    - merge_requests

.deploy:
  script:
    - serverless config credentials --provider aws --key ${KEY} --secret ${SECRET}
    - serverless deploy --stage=${STAGE} --verbose

deploy-master:
  stage: deploy
  extends:
    - .deploy
  only:
    - master
  variables:
    STAGE: prod
    KEY: ${ACCESS_KEY_ID}
    SECRET: ${SECRET_ACCESS_KEY}

deploy-sandbox:
  stage: deploy
  extends:
    - .deploy
  except:
    - master
  only:
    - merge_requests
  variables:
    STAGE: dev
    KEY: ${ACCESS_KEY_ID}
    SECRET: ${SECRET_ACCESS_KEY}
