service: fileparser

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
  countLines:
    handler: handler.countLines
    events:
      - http:
          path: countlines/{url}
          method: get
          request:
            parameters:
              paths:
                url: true